services:
  db:
    image: postgres:18.0
    container_name: ezbot-postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - /tmp/postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"   # опционально для локального доступа с хоста

  redis:
    image: redis:8.2
    container_name: ezbot-redis
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 20
    ports:
      - "6379:6379"   # опционально

  bot:
    image: pubepoh/ez-telegram-bot:0.2
    container_name: ezbot-app
    # Подставляем настройки из .env
    env_file: .env
    environment:
      # Переопределим DSN под docker-сеть
      POSTGRES_DSN: postgresql://postgres:postgres@db:5432/bot
      REDIS_URL: redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
